/**********************************/
/* Table Name: 질문게시글 */
/**********************************/
DROP TABLE QNA_CONTENTS CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE QNA_CONTENTS;

CREATE TABLE QNA_CONTENTS(
		QCON_NO NUMBER(10) NOT NULL PRIMARY KEY,
		CATE_NO NUMBER(10), -- FK
		PRO_NO NUMBER(10),  -- FK
		QCON_NAME VARCHAR2(100) NOT NULL,
		QCON_CONTENTS VARCHAR2(3000),
		QCON_VIEWS NUMBER(7) DEFAULT 0 NOT NULL,
		QCON_BOOKMARK NUMBER(7) DEFAULT 0 NOT NULL,
		QCON_COMMENT NUMBER(7) DEFAULT 0 NOT NULL,
		QCON_DATE DATE NOT NULL,
  FOREIGN KEY (CATE_NO) REFERENCES CATEGORY (CATE_NO),
  FOREIGN KEY (PRO_NO) REFERENCES PROFILE (PRO_NO)
);

COMMENT ON TABLE QNA_CONTENTS is '질문게시글';
COMMENT ON COLUMN QNA_CONTENTS.QCON_NO is '질문게시글 번호';
COMMENT ON COLUMN QNA_CONTENTS.CATE_NO is '카테고리 번호';
COMMENT ON COLUMN QNA_CONTENTS.PRO_NO is '회원 번호';
COMMENT ON COLUMN QNA_CONTENTS.QCON_NAME is '제목';
COMMENT ON COLUMN QNA_CONTENTS.QCON_CONTENTS is '내용';
COMMENT ON COLUMN QNA_CONTENTS.QCON_VIEWS is '조회수';
COMMENT ON COLUMN QNA_CONTENTS.QCON_BOOKMARK is '북마크수';
COMMENT ON COLUMN QNA_CONTENTS.QCON_COMMENT is '댓글수';
COMMENT ON COLUMN QNA_CONTENTS.QCON_DATE is '등록일';


DROP SEQUENCE QNA_CONTENTS_SEQ;

CREATE SEQUENCE QNA_CONTENTS_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 9999999999       -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지
  

SELECT * FROM qna_contents;