/**********************************/
/* Table Name: 팁게시글 */
/**********************************/
DROP TABLE TIP_CONTENTS;

CREATE TABLE TIP_CONTENTS(
		TCON_NO NUMBER(10) NOT NULL PRIMARY KEY,
		CATE_NO NUMBER(10), -- FK
		ADM_NO NUMBER(10),  -- FK
		TCON_IMAGE VARCHAR2(100),
		TCON_SAVED_IMAGE VARCHAR2(100),
		TCON_THUMB_IMAGE VARCHAR2(100),
		TCON_IMAGE_SIZE INT,
		YOUTUBE VARCHAR2(1000),
  FOREIGN KEY (CATE_NO) REFERENCES CATEGORY (CATE_NO),
  FOREIGN KEY (ADM_NO) REFERENCES ADMIN (ADM_NO)
);

COMMENT ON TABLE TIP_CONTENTS is '팁 게시글';
COMMENT ON COLUMN TIP_CONTENTS.TCON_NO is '팁게시글 번호';
COMMENT ON COLUMN TIP_CONTENTS.CATE_NO is '카테고리 번호';
COMMENT ON COLUMN TIP_CONTENTS.ADM_NO is '관리자 번호';
COMMENT ON COLUMN TIP_CONTENTS.TCON_IMAGE is '이미지';
COMMENT ON COLUMN TIP_CONTENTS.TCON_SAVED_IMAGE is '저장된 이미지';
COMMENT ON COLUMN TIP_CONTENTS.TCON_THUMB_IMAGE is 'THUMB 이미지';
COMMENT ON COLUMN TIP_CONTENTS.TCON_IMAGE_SIZE is '이미지 크기';
COMMENT ON COLUMN TIP_CONTENTS.YOUTUBE is '유튜브 링크';


DROP SEQUENCE TIP_CONTENTS_SEQ;

CREATE SEQUENCE TIP_CONTENTS_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 9999999999       -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지

SELECT * FROM tip_contents;