/**********************************/
/* Table Name: 카테고리 */
/**********************************/
DROP TABLE CATEGORY CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
		CATE_NO NUMBER(10) NOT NULL PRIMARY KEY,
		CATE_NAME VARCHAR2(30) NOT NULL,
		CATE_CNT NUMBER(7) DEFAULT 0 NOT NULL,
		CATE_SEQNO NUMBER(5) DEFAULT 0 NOT NULL,
		CATE_VISIBLE CHAR(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON TABLE CATEGORY is '카테고리';
COMMENT ON COLUMN CATEGORY.CATE_NO is '카테고리 번호';
COMMENT ON COLUMN CATEGORY.CATE_NAME is '카테고리 이름';
COMMENT ON COLUMN CATEGORY.CATE_CNT is '관련 자료수';
COMMENT ON COLUMN CATEGORY.CATE_SEQNO is '출력 순서';
COMMENT ON COLUMN CATEGORY.CATE_VISIBLE is '출력 모드';


DROP SEQUENCE CATEGORY_SEQ;

CREATE SEQUENCE CATEGORY_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 9999999999       -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지