/**********************************/
/* Table Name: 질문이미지 */
/**********************************/
DROP TABLE QNA_IMAGE;

CREATE TABLE QNA_IMAGE(
		FILE_NO NUMBER(10) NOT NULL PRIMARY KEY,
		QCON_NO NUMBER(10),
		FILE_ORIGIN_NAME VARCHAR2(100) NOT NULL,
		FILE_UPLOAD_NAME VARCHAR2(100) NOT NULL,
		FILE_THUMB_NAME VARCHAR2(100) NOT NULL,
		FILE_SIZE INT DEFAULT 0 NOT NULL,
		FILE_DATE DATE NOT NULL,
  FOREIGN KEY (QCON_NO) REFERENCES QNA_CONTENTS (QCON_NO)
);