/**********************************/
/* Table Name: 카테고리 */
/**********************************/
CREATE TABLE CATEGORY(
		CATEGORYNO                    		NUMBER(10)		 NOT NULL,
		NATION                        		VARCHAR2(30)		 NOT NULL,
		GENRE                         		VARCHAR2(30)		 DEFAULT '-'		 NOT NULL,
		TITLE                         		VARCHAR2(30)		 DEFAULT '*'		 NOT NULL,
		CNT                           		NUMBER(10)		 DEFAULT 0		 NOT NULL,
		RDATE                         		DATE		 NOT NULL,
		SEQNO                         		NUMBER(5)		 NOT NULL,
		VISIBLE                       		CHAR(1)		 DEFAULT 'N'		 NOT NULL,
		PEOPLE                        		NUMBER(10)		 DEFAULT 0		 NOT NULL
);

COMMENT ON TABLE CATEGORY is '카테고리';
COMMENT ON COLUMN CATEGORY.CATEGORYNO is '카테고리번호';
COMMENT ON COLUMN CATEGORY.NATION is '국가';
COMMENT ON COLUMN CATEGORY.GENRE is '장르';
COMMENT ON COLUMN CATEGORY.TITLE is '제목';
COMMENT ON COLUMN CATEGORY.CNT is '관련자료수';
COMMENT ON COLUMN CATEGORY.RDATE is '등록일';
COMMENT ON COLUMN CATEGORY.SEQNO is '출력순서';
COMMENT ON COLUMN CATEGORY.VISIBLE is '출력모드';
COMMENT ON COLUMN CATEGORY.PEOPLE is '조회수';


/**********************************/
/* Table Name: 회원 */
/**********************************/
CREATE TABLE VIEWER(
		VIEWERNO                      		NUMBER(10)		 NOT NULL,
		NAME                          		VARCHAR2(30)		 NOT NULL,
		PREREVIEW                     		VARCHAR2(30)		 NOT NULL
);

COMMENT ON TABLE VIEWER is '회원';
COMMENT ON COLUMN VIEWER.VIEWERNO is '회원번호';
COMMENT ON COLUMN VIEWER.NAME is '이름';
COMMENT ON COLUMN VIEWER.PREREVIEW is '이전 댓글';


/**********************************/
/* Table Name: 컨텐츠 */
/**********************************/
CREATE TABLE COTENTS(
		CONTENTSNO                    		NUMBER(10)		 NOT NULL,
		CATEGORYNO                    		NUMBER(10)		 NULL ,
		VIEWERNO                      		NUMBER(10)		 NULL ,
		DESCRIPTION                   		LONG		 NOT NULL,
		ROUND                         		INTEGER(30)		 NOT NULL
);

COMMENT ON TABLE COTENTS is '컨텐츠';
COMMENT ON COLUMN COTENTS.CONTENTSNO is '컨텐츠번호';
COMMENT ON COLUMN COTENTS.CATEGORYNO is '카테고리번호';
COMMENT ON COLUMN COTENTS.VIEWERNO is '회원번호';
COMMENT ON COLUMN COTENTS.DESCRIPTION is '설명';
COMMENT ON COLUMN COTENTS.ROUND is '회차';


/**********************************/
/* Table Name: 장르 */
/**********************************/
CREATE TABLE GANRE(
		GANRENO                       		NUMBER(10)		 NOT NULL,
		DRAMA                         		CHAR(1)		 DEFAULT 'Y'		 NOT NULL,
		CONTENTSNO                    		NUMBER(10)		 NULL ,
		KOREANO                       		NUMBER(10)		 NULL ,
		HISTORY                       		CHAR(1)		 DEFAULT 'Y'		 NOT NULL,
		ACTION                        		CHAR(1)		 DEFAULT 'Y'		 NOT NULL
);

COMMENT ON TABLE GANRE is '장르';
COMMENT ON COLUMN GANRE.GANRENO is '장르번호';
COMMENT ON COLUMN GANRE.DRAMA is '드라마';
COMMENT ON COLUMN GANRE.CONTENTSNO is '컨텐츠번호';
COMMENT ON COLUMN GANRE.KOREANO is '국내번호';
COMMENT ON COLUMN GANRE.HISTORY is '사극';
COMMENT ON COLUMN GANRE.ACTION is '액션';


/**********************************/
/* Table Name: 댓글 */
/**********************************/
CREATE TABLE REVIEW(
		REVIEWNO                      		NUMBER(10)		 NOT NULL,
		GRADE                         		INTEGER(10)		 NOT NULL,
		RDATE                         		DATE		 NOT NULL,
		VIEWERNO                      		NUMBER(10)		 NULL ,
		CONTENTSNO                    		NUMBER(10)		 NULL 
);

COMMENT ON TABLE REVIEW is '댓글';
COMMENT ON COLUMN REVIEW.REVIEWNO is '댓글번호';
COMMENT ON COLUMN REVIEW.GRADE is '평점';
COMMENT ON COLUMN REVIEW.RDATE is '날짜';
COMMENT ON COLUMN REVIEW.VIEWERNO is '회원번호';
COMMENT ON COLUMN REVIEW.CONTENTSNO is '컨텐츠번호';


/**********************************/
/* Table Name: 배우 */
/**********************************/
CREATE TABLE ACTOR(
		ACTORNO                       		NUMBER(10)		 NOT NULL,
		NAME                          		VARCHAR2(30)		 NOT NULL,
		GENDER                        		CHAR(1)		 DEFAULT 'M'		 NOT NULL,
		BIRTHDAY                      		DATE		 NOT NULL,
		NATION                        		VARCHAR2(20)		 NOT NULL,
		CONTENTSNO                    		NUMBER(10)		 NULL 
);

COMMENT ON TABLE ACTOR is '배우';
COMMENT ON COLUMN ACTOR.ACTORNO is '배우';
COMMENT ON COLUMN ACTOR.NAME is '이름';
COMMENT ON COLUMN ACTOR.GENDER is '성별';
COMMENT ON COLUMN ACTOR.BIRTHDAY is '생년월일';
COMMENT ON COLUMN ACTOR.NATION is '국적';
COMMENT ON COLUMN ACTOR.CONTENTSNO is '컨텐츠번호';


/**********************************/
/* Table Name: 역할 */
/**********************************/
CREATE TABLE PART(
		PARTNO                        		NUMBER(10)		 NOT NULL,
		ACTORNO                       		NUMBER(10)		 NULL ,
		CONTENTSNO                    		NUMBER(10)		 NULL 
);

COMMENT ON TABLE PART is '역할';
COMMENT ON COLUMN PART.PARTNO is '역할번호';
COMMENT ON COLUMN PART.ACTORNO is '배우';
COMMENT ON COLUMN PART.CONTENTSNO is '컨텐츠번호';


/**********************************/
/* Table Name: 제작진 */
/**********************************/
CREATE TABLE PRODUCER(
		PRODUCERNO                    		NUMBER(10)		 NOT NULL,
		CONTENTSNO                    		NUMBER(10)		 NULL 
);

COMMENT ON TABLE PRODUCER is '제작진';
COMMENT ON COLUMN PRODUCER.PRODUCERNO is '제작진번호';
COMMENT ON COLUMN PRODUCER.CONTENTSNO is '컨텐츠번호';


/**********************************/
/* Table Name: 감독 */
/**********************************/
CREATE TABLE DIRECTOR(
		DIRECTORNO                    		NUMBER(10)		 NOT NULL,
		NAME                          		VARCHAR2(30)		 NOT NULL,
		GENDER                        		CHAR(1)		 DEFAULT 'M'		 NOT NULL,
		BIRTHDAY                      		DATE		 NOT NULL,
		PRODUCERNO                    		NUMBER(10)		 NULL 
);

COMMENT ON TABLE DIRECTOR is '감독';
COMMENT ON COLUMN DIRECTOR.DIRECTORNO is '감독번호';
COMMENT ON COLUMN DIRECTOR.NAME is '이름';
COMMENT ON COLUMN DIRECTOR.GENDER is '성별';
COMMENT ON COLUMN DIRECTOR.BIRTHDAY is '생년월일';
COMMENT ON COLUMN DIRECTOR.PRODUCERNO is '제작진번호';


/**********************************/
/* Table Name: 주요인물 */
/**********************************/
CREATE TABLE MAIN(
		MAINNO                        		NUMBER(10)		 NOT NULL,
		NAME                          		VARCHAR2(30)		 NOT NULL,
		DESCRIPTION                   		VARCHAR2(30)		 NOT NULL,
		GENDER                        		CHAR(1)		 DEFAULT 'M'		 NOT NULL,
		PARTNO                        		NUMBER(10)		 NULL 
);

COMMENT ON TABLE MAIN is '주요인물';
COMMENT ON COLUMN MAIN.MAINNO is '주요인물번호';
COMMENT ON COLUMN MAIN.NAME is '이름';
COMMENT ON COLUMN MAIN.DESCRIPTION is '설명';
COMMENT ON COLUMN MAIN.GENDER is '성별';
COMMENT ON COLUMN MAIN.PARTNO is '역할번호';


/**********************************/
/* Table Name: 그 외 인물 */
/**********************************/
CREATE TABLE EXTREA(
		EXTRANO                       		NUMBER(10)		 NOT NULL,
		NAME                          		VARCHAR2(30)		 NOT NULL,
		DESCRIPTION                   		VARCHAR2(30)		 NOT NULL,
		GENDER                        		CHAR(1)		 DEFAULT 'M'		 NOT NULL,
		PARTNO                        		NUMBER(10)		 DEFAULT "M"		 NULL 
);

COMMENT ON TABLE EXTREA is '그 외 인물';
COMMENT ON COLUMN EXTREA.EXTRANO is '그외인물번호';
COMMENT ON COLUMN EXTREA.NAME is '이름';
COMMENT ON COLUMN EXTREA.DESCRIPTION is '설명';
COMMENT ON COLUMN EXTREA.GENDER is '성별';
COMMENT ON COLUMN EXTREA.PARTNO is '역할번호';


/**********************************/
/* Table Name: 작가 */
/**********************************/
CREATE TABLE SCENE(
		SCENENO                       		NUMBER(10)		 NOT NULL,
		NAME                          		VARCHAR2(30)		 NOT NULL,
		GENDER                        		CHAR(1)		 DEFAULT 'M'		 NOT NULL,
		DATE                          		DATE		 NOT NULL,
		PRODUCERNO                    		NUMBER(10)		 NULL 
);

COMMENT ON TABLE SCENE is '작가';
COMMENT ON COLUMN SCENE.SCENENO is '작가번호';
COMMENT ON COLUMN SCENE.NAME is '이름';
COMMENT ON COLUMN SCENE.GENDER is '성별';
COMMENT ON COLUMN SCENE.DATE is '생년월일';
COMMENT ON COLUMN SCENE.PRODUCERNO is '제작진번호';



ALTER TABLE CATEGORY ADD CONSTRAINT IDX_CATEGORY_PK PRIMARY KEY (CATEGORYNO);

ALTER TABLE VIEWER ADD CONSTRAINT IDX_VIEWER_PK PRIMARY KEY (VIEWERNO);

ALTER TABLE COTENTS ADD CONSTRAINT IDX_COTENTS_PK PRIMARY KEY (CONTENTSNO);
ALTER TABLE COTENTS ADD CONSTRAINT IDX_COTENTS_FK0 FOREIGN KEY (CATEGORYNO) REFERENCES CATEGORY (CATEGORYNO);
ALTER TABLE COTENTS ADD CONSTRAINT IDX_COTENTS_FK1 FOREIGN KEY (VIEWERNO) REFERENCES VIEWER (VIEWERNO);

ALTER TABLE GANRE ADD CONSTRAINT IDX_GANRE_PK PRIMARY KEY (GANRENO);
ALTER TABLE GANRE ADD CONSTRAINT IDX_GANRE_FK0 FOREIGN KEY (CONTENTSNO) REFERENCES COTENTS (CONTENTSNO);

ALTER TABLE REVIEW ADD CONSTRAINT IDX_REVIEW_PK PRIMARY KEY (REVIEWNO);
ALTER TABLE REVIEW ADD CONSTRAINT IDX_REVIEW_FK0 FOREIGN KEY (VIEWERNO) REFERENCES VIEWER (VIEWERNO);
ALTER TABLE REVIEW ADD CONSTRAINT IDX_REVIEW_FK1 FOREIGN KEY (CONTENTSNO) REFERENCES COTENTS (CONTENTSNO);

ALTER TABLE ACTOR ADD CONSTRAINT IDX_ACTOR_PK PRIMARY KEY (ACTORNO);
ALTER TABLE ACTOR ADD CONSTRAINT IDX_ACTOR_FK0 FOREIGN KEY (CONTENTSNO) REFERENCES COTENTS (CONTENTSNO);

ALTER TABLE PART ADD CONSTRAINT IDX_PART_PK PRIMARY KEY (PARTNO);
ALTER TABLE PART ADD CONSTRAINT IDX_PART_FK0 FOREIGN KEY (ACTORNO) REFERENCES ACTOR (ACTORNO);
ALTER TABLE PART ADD CONSTRAINT IDX_PART_FK1 FOREIGN KEY (CONTENTSNO) REFERENCES COTENTS (CONTENTSNO);

ALTER TABLE PRODUCER ADD CONSTRAINT IDX_PRODUCER_PK PRIMARY KEY (PRODUCERNO);
ALTER TABLE PRODUCER ADD CONSTRAINT IDX_PRODUCER_FK0 FOREIGN KEY (CONTENTSNO) REFERENCES COTENTS (CONTENTSNO);

ALTER TABLE DIRECTOR ADD CONSTRAINT IDX_DIRECTOR_PK PRIMARY KEY (DIRECTORNO);
ALTER TABLE DIRECTOR ADD CONSTRAINT IDX_DIRECTOR_FK0 FOREIGN KEY (PRODUCERNO) REFERENCES PRODUCER (PRODUCERNO);

ALTER TABLE MAIN ADD CONSTRAINT IDX_MAIN_PK PRIMARY KEY (MAINNO);
ALTER TABLE MAIN ADD CONSTRAINT IDX_MAIN_FK0 FOREIGN KEY (PARTNO) REFERENCES PART (PARTNO);

ALTER TABLE EXTREA ADD CONSTRAINT IDX_EXTREA_PK PRIMARY KEY (EXTRANO);
ALTER TABLE EXTREA ADD CONSTRAINT IDX_EXTREA_FK0 FOREIGN KEY (PARTNO) REFERENCES PART (PARTNO);

ALTER TABLE SCENE ADD CONSTRAINT IDX_SCENE_PK PRIMARY KEY (SCENENO);
ALTER TABLE SCENE ADD CONSTRAINT IDX_SCENE_FK0 FOREIGN KEY (PRODUCERNO) REFERENCES PRODUCER (PRODUCERNO);

