/**********************************/
/* Table Name: 관리자 */
/**********************************/
DROP TABLE ADMIN CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE ADMIN;

CREATE TABLE ADMIN(
		ADM_NO NUMBER(10) NOT NULL PRIMARY KEY,
		CATE_NO NUMBER(10), -- FK
		ADM_ID VARCHAR2(20) NOT NULL,
		ADM_PW VARCHAR2(100) NOT NULL,
		ADM_NAME VARCHAR2(5) NOT NULL,
		ADM_DATE DATE NOT NULL,
		ADM_GRADE NUMBER(2) NOT NULL,
  FOREIGN KEY (CATE_NO) REFERENCES CATEGORY (CATE_NO)
);

COMMENT ON TABLE ADMIN is '관리자';
COMMENT ON COLUMN ADMIN.ADM_NO is '관리자 번호';
COMMENT ON COLUMN ADMIN.CATE_NO is '카테고리 번호';
COMMENT ON COLUMN ADMIN.ADM_ID is '관리자 아이디';
COMMENT ON COLUMN ADMIN.ADM_PW is '관리자 비밀번호';
COMMENT ON COLUMN ADMIN.ADM_NAME is '관리자 이름';
COMMENT ON COLUMN ADMIN.ADM_DATE is '가입일';
COMMENT ON COLUMN ADMIN.ADM_GRADE is '등급';


DROP SEQUENCE ADMIN_SEQ;

CREATE SEQUENCE ADMIN_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 9999999999       -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지
  

SELECT * FROM admin;