/**********************************/
/* Table Name: 질문게시글댓글 */
/**********************************/
DROP TABLE QNA_COMMENT;

CREATE TABLE QNA_COMMENT(
		QCMT_NO NUMBER(10) NOT NULL PRIMARY KEY,
		PRO_NO NUMBER(10),
		QCON_NO NUMBER(10),
		QCMT_CONTENTS VARCHAR2(300) NOT NULL,
		QCMT_DATE DATE NOT NULL,
  FOREIGN KEY (QCON_NO) REFERENCES QNA_CONTENTS (QCON_NO),
  FOREIGN KEY (PRO_NO) REFERENCES PROFILE (PRO_NO)
);