/**********************************/
/* Table Name: 회원 */
/**********************************/
DROP TABLE PROFILE CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE PROFILE;

CREATE TABLE PROFILE(
		PRO_NO NUMBER(10) NOT NULL PRIMARY KEY,
		PRO_ID VARCHAR2(60) NOT NULL,
		PRO_PW VARCHAR2(100) NOT NULL,
		PRO_NICKNAME VARCHAR2(8) NOT NULL,
		PRO_TEL VARCHAR2(14),
		PRO_AGE VARCHAR2(6),
		PRO_DATE DATE NOT NULL,
		PRO_GRADE NUMBER(2) NOT NULL,
		PRO_IMAGE VARCHAR2(100),
		PRO_SAVED_IMAGE VARCHAR2(100),
		PRO_THUMB_IMAGE VARCHAR2(100),
		PRO_IMAGE_SIZE NUMBER(10)
);