/**********************************/
/* Table Name: 회원 */
/**********************************/
DROP TABLE PROFILE CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE PROFILE;

CREATE TABLE PROFILE(
		PRO_NO NUMBER(10) NOT NULL PRIMARY KEY,
		PRO_ID VARCHAR2(60) NOT NULL,
		PRO_PW VARCHAR2(100) NOT NULL,
		PRO_NICKNAME VARCHAR2(8) NOT NULL,
		PRO_TEL VARCHAR2(14),
		PRO_AGE VARCHAR2(6),
		PRO_DATE DATE NOT NULL,
		PRO_GRADE NUMBER(2) NOT NULL,
		PRO_IMAGE VARCHAR2(100),
		PRO_SAVED_IMAGE VARCHAR2(100),
		PRO_THUMB_IMAGE VARCHAR2(100),
		PRO_IMAGE_SIZE NUMBER(10)
);
COMMENT ON TABLE PROFILE is '회원';
COMMENT ON COLUMN PROFILE.PRO_NO is '회원번호';
COMMENT ON COLUMN PROFILE.PRO_ID is '아이디';
COMMENT ON COLUMN PROFILE.PRO_PW is '비밀번호';
COMMENT ON COLUMN PROFILE.PRO_NICKNAME is '닉네임';
COMMENT ON COLUMN PROFILE.PRO_TEL is '전화번호';
COMMENT ON COLUMN PROFILE.PRO_AGE is '연령대';
COMMENT ON COLUMN PROFILE.PRO_DATE is '가입일';
COMMENT ON COLUMN PROFILE.PRO_GRADE is '등급';
COMMENT ON COLUMN PROFILE.PRO_IMAGE is '프로필사진';
COMMENT ON COLUMN PROFILE.PRO_SAVED_IMAGE is '저장된프로필사진';
COMMENT ON COLUMN PROFILE.PRO_THUMB_IMAGE is '프로필사진THUMB';
COMMENT ON COLUMN PROFILE.PRO_IMAGE_SIZE is '프로필사진크기';

DROP SEQUENCE PROFILE_SEQ;

 CREATE SEQUENCE PROFILE_SEQ
   START WITH 1        
   INCREMENT BY 1       
   MAXVALUE 9999999999 
   CACHE 2              
   NOCYCLE;             
